# Generated by Django 5.0.1 on 2024-01-09 18:00

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('source', django_countries.fields.CountryField(max_length=2)),
                ('destination', django_countries.fields.CountryField(max_length=2)),
                ('proprietaire', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=20)),
                ('etat', models.CharField(choices=[('En recuperation', 'En recuperation'), ('Au depot', 'Au depot'), ('Au chargement', 'Au Chargement'), ("En cours d'expedition", "En cours d'expedition"), ('En cours de livraison', 'En cours de livraison'), ('Colis livré', 'Colis livré')], max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=10)),
            ],
            options={
                'verbose_name': 'Colis',
                'verbose_name_plural': 'Coliss',
            },
        ),
    ]
