# Generated by Django 5.0.1 on 2024-01-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_colis_destination_alter_colis_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='colis',
            name='destination',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='colis',
            name='source',
            field=models.CharField(max_length=150),
        ),
    ]
